{{- if .Values.httproute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.httproute.name }}
spec:
  parentRefs:
    - name: default-envoy-gw
      namespace: envoy-gateway-system
  hostnames:
  {{- range .Values.httproute.hostnames }}
    - {{ . }}    
  {{- end }}
  rules:
    - backendRefs:
       {{- toYaml .Values.httproute.rules.backendrefs | nindent 8 }}
      matches:
        {{- toYaml .Values.httproute.rules.matches | nindent 10 }}
{{- end }}
